//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_WebService_GT.ServiceReference_secure {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_secure.nostra_serviceSoap")]
    public interface nostra_serviceSoap {
        
        // CODEGEN: Generating message contract since element name ip from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search", ReplyAction="*")]
        WB_WebService_GT.ServiceReference_secure.SearchResponse Search(WB_WebService_GT.ServiceReference_secure.SearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search", ReplyAction="*")]
        System.Threading.Tasks.Task<WB_WebService_GT.ServiceReference_secure.SearchResponse> SearchAsync(WB_WebService_GT.ServiceReference_secure.SearchRequest request);
        
        // CODEGEN: Generating message contract since element name ip from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RoadSnap", ReplyAction="*")]
        WB_WebService_GT.ServiceReference_secure.RoadSnapResponse RoadSnap(WB_WebService_GT.ServiceReference_secure.RoadSnapRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RoadSnap", ReplyAction="*")]
        System.Threading.Tasks.Task<WB_WebService_GT.ServiceReference_secure.RoadSnapResponse> RoadSnapAsync(WB_WebService_GT.ServiceReference_secure.RoadSnapRequest request);
        
        // CODEGEN: Generating message contract since element name ip from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Text", ReplyAction="*")]
        WB_WebService_GT.ServiceReference_secure.TextResponse Text(WB_WebService_GT.ServiceReference_secure.TextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Text", ReplyAction="*")]
        System.Threading.Tasks.Task<WB_WebService_GT.ServiceReference_secure.TextResponse> TextAsync(WB_WebService_GT.ServiceReference_secure.TextRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search", Namespace="http://tempuri.org/", Order=0)]
        public WB_WebService_GT.ServiceReference_secure.SearchRequestBody Body;
        
        public SearchRequest() {
        }
        
        public SearchRequest(WB_WebService_GT.ServiceReference_secure.SearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ip;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        public SearchRequestBody() {
        }
        
        public SearchRequestBody(string ip, string token) {
            this.ip = ip;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchResponse", Namespace="http://tempuri.org/", Order=0)]
        public WB_WebService_GT.ServiceReference_secure.SearchResponseBody Body;
        
        public SearchResponse() {
        }
        
        public SearchResponse(WB_WebService_GT.ServiceReference_secure.SearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SearchResult;
        
        public SearchResponseBody() {
        }
        
        public SearchResponseBody(bool SearchResult) {
            this.SearchResult = SearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RoadSnapRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RoadSnap", Namespace="http://tempuri.org/", Order=0)]
        public WB_WebService_GT.ServiceReference_secure.RoadSnapRequestBody Body;
        
        public RoadSnapRequest() {
        }
        
        public RoadSnapRequest(WB_WebService_GT.ServiceReference_secure.RoadSnapRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RoadSnapRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ip;
        
        public RoadSnapRequestBody() {
        }
        
        public RoadSnapRequestBody(string ip) {
            this.ip = ip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RoadSnapResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RoadSnapResponse", Namespace="http://tempuri.org/", Order=0)]
        public WB_WebService_GT.ServiceReference_secure.RoadSnapResponseBody Body;
        
        public RoadSnapResponse() {
        }
        
        public RoadSnapResponse(WB_WebService_GT.ServiceReference_secure.RoadSnapResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RoadSnapResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RoadSnapResult;
        
        public RoadSnapResponseBody() {
        }
        
        public RoadSnapResponseBody(bool RoadSnapResult) {
            this.RoadSnapResult = RoadSnapResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Text", Namespace="http://tempuri.org/", Order=0)]
        public WB_WebService_GT.ServiceReference_secure.TextRequestBody Body;
        
        public TextRequest() {
        }
        
        public TextRequest(WB_WebService_GT.ServiceReference_secure.TextRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TextRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ip;
        
        public TextRequestBody() {
        }
        
        public TextRequestBody(string ip) {
            this.ip = ip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TextResponse", Namespace="http://tempuri.org/", Order=0)]
        public WB_WebService_GT.ServiceReference_secure.TextResponseBody Body;
        
        public TextResponse() {
        }
        
        public TextResponse(WB_WebService_GT.ServiceReference_secure.TextResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TextResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool TextResult;
        
        public TextResponseBody() {
        }
        
        public TextResponseBody(bool TextResult) {
            this.TextResult = TextResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface nostra_serviceSoapChannel : WB_WebService_GT.ServiceReference_secure.nostra_serviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class nostra_serviceSoapClient : System.ServiceModel.ClientBase<WB_WebService_GT.ServiceReference_secure.nostra_serviceSoap>, WB_WebService_GT.ServiceReference_secure.nostra_serviceSoap {
        
        public nostra_serviceSoapClient() {
        }
        
        public nostra_serviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public nostra_serviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public nostra_serviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public nostra_serviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WB_WebService_GT.ServiceReference_secure.SearchResponse WB_WebService_GT.ServiceReference_secure.nostra_serviceSoap.Search(WB_WebService_GT.ServiceReference_secure.SearchRequest request) {
            return base.Channel.Search(request);
        }
        
        public bool Search(string ip, string token) {
            WB_WebService_GT.ServiceReference_secure.SearchRequest inValue = new WB_WebService_GT.ServiceReference_secure.SearchRequest();
            inValue.Body = new WB_WebService_GT.ServiceReference_secure.SearchRequestBody();
            inValue.Body.ip = ip;
            inValue.Body.token = token;
            WB_WebService_GT.ServiceReference_secure.SearchResponse retVal = ((WB_WebService_GT.ServiceReference_secure.nostra_serviceSoap)(this)).Search(inValue);
            return retVal.Body.SearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WB_WebService_GT.ServiceReference_secure.SearchResponse> WB_WebService_GT.ServiceReference_secure.nostra_serviceSoap.SearchAsync(WB_WebService_GT.ServiceReference_secure.SearchRequest request) {
            return base.Channel.SearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<WB_WebService_GT.ServiceReference_secure.SearchResponse> SearchAsync(string ip, string token) {
            WB_WebService_GT.ServiceReference_secure.SearchRequest inValue = new WB_WebService_GT.ServiceReference_secure.SearchRequest();
            inValue.Body = new WB_WebService_GT.ServiceReference_secure.SearchRequestBody();
            inValue.Body.ip = ip;
            inValue.Body.token = token;
            return ((WB_WebService_GT.ServiceReference_secure.nostra_serviceSoap)(this)).SearchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WB_WebService_GT.ServiceReference_secure.RoadSnapResponse WB_WebService_GT.ServiceReference_secure.nostra_serviceSoap.RoadSnap(WB_WebService_GT.ServiceReference_secure.RoadSnapRequest request) {
            return base.Channel.RoadSnap(request);
        }
        
        public bool RoadSnap(string ip) {
            WB_WebService_GT.ServiceReference_secure.RoadSnapRequest inValue = new WB_WebService_GT.ServiceReference_secure.RoadSnapRequest();
            inValue.Body = new WB_WebService_GT.ServiceReference_secure.RoadSnapRequestBody();
            inValue.Body.ip = ip;
            WB_WebService_GT.ServiceReference_secure.RoadSnapResponse retVal = ((WB_WebService_GT.ServiceReference_secure.nostra_serviceSoap)(this)).RoadSnap(inValue);
            return retVal.Body.RoadSnapResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WB_WebService_GT.ServiceReference_secure.RoadSnapResponse> WB_WebService_GT.ServiceReference_secure.nostra_serviceSoap.RoadSnapAsync(WB_WebService_GT.ServiceReference_secure.RoadSnapRequest request) {
            return base.Channel.RoadSnapAsync(request);
        }
        
        public System.Threading.Tasks.Task<WB_WebService_GT.ServiceReference_secure.RoadSnapResponse> RoadSnapAsync(string ip) {
            WB_WebService_GT.ServiceReference_secure.RoadSnapRequest inValue = new WB_WebService_GT.ServiceReference_secure.RoadSnapRequest();
            inValue.Body = new WB_WebService_GT.ServiceReference_secure.RoadSnapRequestBody();
            inValue.Body.ip = ip;
            return ((WB_WebService_GT.ServiceReference_secure.nostra_serviceSoap)(this)).RoadSnapAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WB_WebService_GT.ServiceReference_secure.TextResponse WB_WebService_GT.ServiceReference_secure.nostra_serviceSoap.Text(WB_WebService_GT.ServiceReference_secure.TextRequest request) {
            return base.Channel.Text(request);
        }
        
        public bool Text(string ip) {
            WB_WebService_GT.ServiceReference_secure.TextRequest inValue = new WB_WebService_GT.ServiceReference_secure.TextRequest();
            inValue.Body = new WB_WebService_GT.ServiceReference_secure.TextRequestBody();
            inValue.Body.ip = ip;
            WB_WebService_GT.ServiceReference_secure.TextResponse retVal = ((WB_WebService_GT.ServiceReference_secure.nostra_serviceSoap)(this)).Text(inValue);
            return retVal.Body.TextResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WB_WebService_GT.ServiceReference_secure.TextResponse> WB_WebService_GT.ServiceReference_secure.nostra_serviceSoap.TextAsync(WB_WebService_GT.ServiceReference_secure.TextRequest request) {
            return base.Channel.TextAsync(request);
        }
        
        public System.Threading.Tasks.Task<WB_WebService_GT.ServiceReference_secure.TextResponse> TextAsync(string ip) {
            WB_WebService_GT.ServiceReference_secure.TextRequest inValue = new WB_WebService_GT.ServiceReference_secure.TextRequest();
            inValue.Body = new WB_WebService_GT.ServiceReference_secure.TextRequestBody();
            inValue.Body.ip = ip;
            return ((WB_WebService_GT.ServiceReference_secure.nostra_serviceSoap)(this)).TextAsync(inValue);
        }
    }
}
